### ISSUE TITLE
tr not working

### ISSUE THREAD

**Issue by DaryeDev** [Drimix20/Flow.Launcher.Plugin.DirectTranslate#13]
Flow Launcher version: 1.18.0
OS Version: 22631.3737
IntPtr Length: 8
x64: True

Python Path: C:\Users\dario\AppData\Local\Programs\Python\Python312\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 06/18/2024 14:30:38
Exception:
Flow.Launcher.Plugin.DirectTranslate Exception: 
Websites: https://github.com/Drimix20/Flow.Launcher.Plugin.DirectTranslate
Author: Drimix20
Version: 2.1.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\dario\AppData\Roaming\FlowLauncher\Plugins\Direct Translate-2.1.0\main.py", line 16, in <module>
    from plugin import Main
  File "C:\Users\dario\AppData\Roaming\FlowLauncher\Plugins\Direct Translate-2.1.0\plugin\__init__.py", line 27, in <module>
    from plugin.ui import Main
  File "C:\Users\dario\AppData\Roaming\FlowLauncher\Plugins\Direct Translate-2.1.0\plugin\ui.py", line 8, in <module>
    from googletrans import Translator
  File "C:\Users\dario\AppData\Roaming\FlowLauncher\Plugins\Direct Translate-2.1.0\lib\googletrans\__init__.py", line 6, in <module>
    from googletrans.client import Translator
  File "C:\Users\dario\AppData\Roaming\FlowLauncher\Plugins\Direct Translate-2.1.0\lib\googletrans\client.py", line 27, in <module>
    class Translator:
  File "C:\Users\dario\AppData\Roaming\FlowLauncher\Plugins\Direct Translate-2.1.0\lib\googletrans\client.py", line 57, in Translator
    proxies: typing.Dict[str, httpcore.SyncHTTPTransport] = None,
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'httpcore' has no attribute 'SyncHTTPTransport'

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\dario\AppData\Roaming\FlowLauncher\Plugins\Direct Translate-2.1.0\main.py", line 16, in <module>
    from plugin import Main
  File "C:\Users\dario\AppData\Roaming\FlowLauncher\Plugins\Direct Translate-2.1.0\plugin\__init__.py", line 27, in <module>
    from plugin.ui import Main
  File "C:\Users\dario\AppData\Roaming\FlowLauncher\Plugins\Direct Translate-2.1.0\plugin\ui.py", line 8, in <module>
    from googletrans import Translator
  File "C:\Users\dario\AppData\Roaming\FlowLauncher\Plugins\Direct Translate-2.1.0\lib\googletrans\__init__.py", line 6, in <module>
    from googletrans.client import Translator
  File "C:\Users\dario\AppData\Roaming\FlowLauncher\Plugins\Direct Translate-2.1.0\lib\googletrans\client.py", line 27, in <module>
    class Translator:
  File "C:\Users\dario\AppData\Roaming\FlowLauncher\Plugins\Direct Translate-2.1.0\lib\googletrans\client.py", line 57, in Translator
    proxies: typing.Dict[str, httpcore.SyncHTTPTransport] = None,
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'httpcore' has no attribute 'SyncHTTPTransport'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 249
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 249
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 264
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 196
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 230
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 224
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 307
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2024-06-18.txt](https://github.com/user-attachments/files/15886584/2024-06-18.txt)

**Comment by spectop** [comment]
u can open this file `C:\Users\dario\AppData\Roaming\FlowLauncher\Plugins\Direct Translate-2.1.0\lib\googletrans\client.py`
and replace `httpcore.SyncHTTPTransport` with `httpcore.AsyncHTTPProxy`
