### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by Drimix20** [Drimix20/Flow.Launcher.Plugin.DirectTranslate#2]
Error below appears when user give input slowly.

Flow Launcher version: 1.8.2
OS Version: Microsoft Windows NT 10.0.19042.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 09/27/2021 09:56:53
Exception:
System.IO.InvalidDataException: Direct Translate|Traceback (most recent call last):
  File "C:\Users\drimalm\AppData\Local\FlowLauncher\app-1.8.2\Plugins\Flow.Launcher.Plugin.DirectTranslate\main.py", line 50, in <module>
    Translate()
  File "C:\Users\drimalm\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flowlauncher\FlowLauncher.py", line 30, in __init__
    results = request_method(*request_parameters)
  File "C:\Users\drimalm\AppData\Local\FlowLauncher\app-1.8.2\Plugins\Flow.Launcher.Plugin.DirectTranslate\main.py", line 43, in query
    return translate(query)
  File "C:\Users\drimalm\AppData\Local\FlowLauncher\app-1.8.2\Plugins\Flow.Launcher.Plugin.DirectTranslate\main.py", line 11, in translate
    to_lang = splitted[1]
IndexError: list index out of range

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 261
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 275
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 286
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass111_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 563
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 564
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Drimix20** [comment]
Fixed by merge of _Migrate to new python plugin structure_. Parameters are verified and help message is shown when there is wrong number of parameters.
